ExpandState XML saving
AdamsLair/winforms pull request #7
Opened 2018-05-25 06:36 UTC by deanljohnson

Added the ability to save/load ExpandState objects from XML.

Part of work on [this Duality feature](https://github.com/AdamsLair/duality/issues/244).

2018-05-26 11:59 UTC, ilexp requested changes

2018-05-26 11:59 UTC, ilexp commented on WinForms/PropertyEditing/PropertyGrid.cs
> +			node.SetElementValue("ExpandedNodes", expandedString);
A comma-separated list is a very un-XML way of expressing a list of values. Can we do an element list instead? Something like:

```xml
<ExpendedNodes>
  <NodeId>Foo</NodeId>
  <NodeId>Bar</NodeId>
  ...
</ExpandedNodes>
```

2018-05-26 20:26 UTC, deanljohnson commented
Nodes are now stored as a list of elements.

2018-05-27 12:55 UTC, ilexp approved these changes
Thanks!

2018-05-27 12:56 UTC, merged